// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/expense-variants/Cockpit.tsx": () => import("../components/mockups/expense-variants/Cockpit.tsx"),
  "./components/mockups/expense-variants/Envelope.tsx": () => import("../components/mockups/expense-variants/Envelope.tsx"),
  "./components/mockups/expense-variants/ReportCard.tsx": () => import("../components/mockups/expense-variants/ReportCard.tsx"),
  "./components/mockups/expense-variants/Wizard.tsx": () => import("../components/mockups/expense-variants/Wizard.tsx")
};
